services:
  mysql:
    container_name: mysql-1
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=restrodb'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=user'
    ports:
      - '3306:3306'
    command: --port 3306
    restart: always
